### ISSUE TITLE
Feature: Display leaderboards in the app

### ISSUE THREAD

**Issue by jpaulobneto** [DavidFrahm/wakatime-mobile#7]
I suggested in community the implementation of the leaderboards feature in the app. I'm waiting for the endpoint creation in order to implement this feature. What do you think?

**Comment by DavidFrahm** [comment]
I personally don't think leaderboards are a positive thing. Its not a good thing to spend all your time programming.

But you should check with WakaTime users who have seen the leaderboard on the website. Do they like it?  Do they want it in the mobile app?

Maybe we should test out a feature where users could choose what charts they want to see in the mobile app?  It could default to all, since we don't have a ton, but then allow the charts to be removed.  Possibly also re-arrange the order.

We should separate these ideas into individual GitHub issues, labeled as 'enhancements'.  I'm away on vacation, so do you want to do that?  (If you think these ideas are worth discussing further)

**Comment by DavidFrahm** [comment]
The primary repo was moved to https://github.com/wakatime/wakatime-mobile, so you'll need to submit a PR there.  I'm going to remove this repo soon.
